#服务器配置
server:
          servlet:
            context-path: /demo
          port: 8888

#数据库配置
spring:
    datasource:
        url: jdbc:mysql://118.24.216.235:3306/wechargame?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false
        username: app
        password: e2Z*YshMNY
        driver-class-name: com.mysql.cj.jdbc.Driver

#mybatis配置
mybatis:
  config-location: classpath:mybatis/mybatis-config.xml
  mapper-locations: classpath:mapper/*.xml

#日志配置
  logging:
    config: classpath:log/logback-boot.xml

#thymeleaf配置
thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: utf-8
    mode: HTML5